# BASE CONFIG: applies to all environments, does not work alone
# See: https://docs.docker.com/compose/extends/

# Extension fields
# See: https://docs.docker.com/compose/compose-file/#extension-fields
x-hubble-image: &hubble-image hubble:0.9

services:
  nginx:
    image: nginx:1.17
    container_name: webb-nginx
    restart: always
    depends_on:
      - web
    volumes:
      - statics:/home/webbadm/static

  web:
    image: *hubble-image
    container_name: webb
    restart: always
    environment:
      SERVICE_TYPE: "web"
    volumes:
      - statics:/home/webbadm/static
    expose:
      - "8000"

  broker:
    image: rabbitmq:3.8.3
    container_name: webb-broker
    restart: always

  celery:
    image: *hubble-image
    container_name: webb-celery
    restart: always
    command:
      [
        "celery",
        "--app=webb",
        "--concurrency=8",
        "--hostname=worker1@%h",
        "--loglevel=INFO",
        "--queues=celery",
        "worker",
      ]
    depends_on:
      - web
      - broker

  flower:
    image: *hubble-image
    container_name: webb-flower
    restart: always
    # TODO: Change url prefix to /admin/tasks when having nginx proxy
    command:
      [
        "celery",
        "--app=webb",
        "--concurrency=8",
        "--db=/home/webbadm/tmp/flowerdb",
        "--persistent",
        "--port=5555",
        "flower",
      ]
    depends_on:
      - broker
      - web

  beat:
    image: *hubble-image
    container_name: webb-beat
    restart: always
    command:
      [
        "celery",
        "--app=webb",
        "--loglevel=INFO",
        "--pidfile=/home/webbadm/tmp/beat.pid",
        "beat",
      ]
    depends_on:
      - broker
      - web

volumes:
  statics:
