# DEV CONFIG: 'docker compose up' reads it automatically along with the docker-compose.yml file
# See: https://docs.docker.com/compose/extends/

x-common: &common
  build: .
  environment:
    ENVIRONMENT: "prod"
    # The following variables are taken directly from shell env variables (Keep them empty)
    DJANGO_SECRET_KEY:
    DATABASE_URL:
    RABBITMQ_USER:
    RABBITMQ_PASS:
    CDN_STORAGE_USERNAME:
    CDN_STORAGE_PASSWORD:
    CDN_API_LOGIN:
    CDN_API_PASSWORD:
    CDN_API_TOKEN:
    EMAIL_USER:
    EMAIL_PASSWORD:
    DOMAIN:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_STORAGE_BUCKET_NAME:
    AWS_S3_REGION_NAME:
    AWS_S3_ENDPOINT_URL:
    AWS_S3_CUSTOM_DOMAIN:
    INTERNAL_IPS:
  volumes:
    - /mnt/volume-nyc1-02/web/media:/home/webbadm/media
    - /mnt/volume-nyc1-02/web/import:/home/webbadm/import
    - /mnt/volume-nyc1-02/web/tmp:/home/webbadm/tmp

    # The SSH key and known_hosts is required to push files to CDN77 Storage, See README
    - ./config/.ssh:/home/webbadm/.ssh
    - ./config/youtube:/home/webbadm/config/youtube

services:
  nginx:
    volumes:
      # Read only config volume
      - ./config/nginx-devserver/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx-devserver/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx-common/snippets:/etc/nginx/snippets:ro
      - /mnt/volume-nyc1-02/web/media:/home/webbadm/media:ro
      - ./config/certbot/www:/var/www/certbot/:ro
      - ./config/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    container_name: webb-certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt:rw
      - ./config/certbot/www:/var/www/certbot:rw
    command:
      certonly --webroot -w /var/www/certbot --force-renewal --email encisosystemsmantis@gmail.com -d webb-staging.encisosystems.com --agree-tos --cert-name webb-staging.encisosystems.com

  web:
    <<: *common
    command: ["./scripts/command-devserver.sh"]

  broker:
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  celery: *common

  flower:
    <<: *common
    command:
      [
        "celery",
        "--app=webb",
        "--concurrency=8",
        "--db=/home/webbadm/tmp/flowerdb",
        "--persistent",
        "--port=5555",
        "--url_prefix=admin/tasks",
        "flower",
      ]
    expose:
      - "5555"

  beat: *common

  cache:
    image: memcached:latest
    container_name: webb-cache
    environment:
      MEMCACHED_CACHE_SIZE: 1024
    hostname: cache
    expose:
      - "11211"
