version: "3.4"

# DEV CONFIG: 'docker-compose up' reads it automatically along with the docker-compose.yml file
# See: https://docs.docker.com/compose/extends/

x-common: &common
  build: .
  environment:
    ENVIRONMENT: "dev"
    URLS_BASEPATH: "public"
  restart: "no"
  volumes:
    - ./spacetelescope:/home/hubbleadm/spacetelescope
    - ./local:/home/hubbleadm/local
    - ./htmlcov:/home/hubbleadm/htmlcov
    - ./docs/static:/home/hubbleadm/docs/static
    - ./test-utils:/home/hubbleadm/test-utils
    - ./test-utils/sitecustomize.py:/home/hubbleadm/sitecustomize.py
    - ./.coveragerc:/home/hubbleadm/.coveragerc
    - ./.coveragerc-parallel:/home/hubbleadm/.coveragerc-parallel

services:
  web:
    <<: *common
    depends_on: 
      - cache
    command: ["./scripts/command-dev.sh"]
    ports:
      - "8000:8000"

  broker:
    restart: "no"

  celery: *common

  flower:
    <<: *common
    ports:
      - "5555:5555"

  beat: *common

  cache:
    image: memcached:latest
    container_name: hubble-cache
    environment:
      MEMCACHED_CACHE_SIZE: 1024
    hostname: cache
    

  db:
    restart: "no"
    environment:
      POSTGRES_DB: hubble
      POSTGRES_USER: hubble
      POSTGRES_PASSWORD: hubble
    ports:
      - "50000:5432"
